     Info:  Nimble data file "/home/runner/.nimble/nimbledata2.json" has been loaded.
    Reading official package list
Downloading https://github.com/fallingduck/asyncpythonfile-nim using git
    Cloning latest tagged version: v0.1.0
open('/workspace/destdir/ssl/openssl.cnf', 32768, 0x00000000000001b6)
open('/home/runner/.config/nimble/nimble.ini', 557056, 0x00000000000001b6)
open('/home/runner/.config/babel/babel.ini', 557056, 0x00000000000001b6)
open('/home/runner/.nimble/nimbledata2.json', 557056, 0x00000000000001b6)
writev(1, 0x00007ffd2afe48a0, 2)
open('/home/runner/work/nim_packages_security_audit/nim_packages_security_audit', 622592, 0x0000000000000000)
writev(1, 0x00007ffd2afe34d0, 2)
open('/home/runner/.nimble/packages_official.json', 557056, 0x00000000000001b6)
mkdir('/tmp/', 0x00000000000001ff)
mkdir('/tmp/nimble_2477/', 0x00000000000001ff)
mkdir('/tmp/nimble_2477/githubcom_fallingduckasyncpythonfilenim', 0x00000000000001ff)
open('/tmp/nimble_2477/githubcom_fallingduckasyncpythonfilenim', 622592, 0x0000000000000000)
writev(1, 0x00007ffd2afe3590, 2)
open('/tmp/nimble_2477/githubcom_fallingduckasyncpythonfilenim', 622592, 0x0000000000000000)
rmdir('/tmp/nimble_2477/githubcom_fallingduckasyncpythonfilenim')
writev(1, 0x00007ffd2afe3480, 2)
mkdir(94506599393152, 0x00000000000001ff)
Error tracing process: readBytes(0x000055f408492780, 256) error: [Errno 5] Input/output error.
