      Info: Package cache path /home/runner/.nimble/pkgcache
     Info:  Nimble data file "/home/runner/.nimble/nimbledata2.json" has been loaded.
    Reading official package list
Downloading https://github.com/jaredmontoya/pyopenai using git
    Cloning latest tagged version: 0.2.0
open('/workspace/destdir/ssl/openssl.cnf', 32768, 0x00000000000001b6)
open('/home/runner/.config/nimble/nimble.ini', 557056, 0x00000000000001b6)
open('/home/runner/.config/babel/babel.ini', 557056, 0x00000000000001b6)
writev(1, 0x00007fff6204aae0, 2)
open('/home/runner/.nimble/nimbledata2.json', 557056, 0x00000000000001b6)
writev(1, 0x00007fff6204abb0, 2)
writev(1, 0x00007ffdf1cd7b60, 2)
writev(1, 0x00007ffdf1cd7bf0, 2)
writev(1, 0x00007ffdf1cd7bf0, 2)
writev(1, 0x00007ffdf1cd7bf0, 2)
writev(1, 0x00007fff620496d0, 2)
open('/home/runner/.nimble/packages_official.json', 557056, 0x00000000000001b6)
mkdir('/home/', 0x00000000000001ff)
mkdir('/home/runner/', 0x00000000000001ff)
mkdir('/home/runner/.nimble/', 0x00000000000001ff)
mkdir('/home/runner/.nimble/pkgcache/', 0x00000000000001ff)
mkdir('/home/runner/.nimble/pkgcache/githubcom_jaredmontoyapyopenai', 0x00000000000001ff)
open('/home/runner/.nimble/pkgcache/githubcom_jaredmontoyapyopenai', 622592, 0x0000000000000000)
writev(1, 0x00007fff620497c0, 2)
open('/home/runner/.nimble/pkgcache/githubcom_jaredmontoyapyopenai', 622592, 0x0000000000000000)
rmdir('/home/runner/.nimble/pkgcache/githubcom_jaredmontoyapyopenai')
writev(1, 0x00007fff620496b0, 2)
mkdir(93858422405968, 0x00000000000001ff)
Error tracing process: readBytes(0x0000555d1ded3b50, 256) error: [Errno 5] Input/output error.
