     Info:  Nimble data file "/home/runner/.nimble/nimbledata2.json" has been loaded.
    Reading official package list
Downloading https://github.com/stisa/jupyternim using git
    Cloning latest tagged version: 0.8.0
open('/workspace/destdir/ssl/openssl.cnf', 32768, 0x00000000000001b6)
open('/home/runner/.config/nimble/nimble.ini', 557056, 0x00000000000001b6)
open('/home/runner/.config/babel/babel.ini', 557056, 0x00000000000001b6)
open('/home/runner/.nimble/nimbledata2.json', 557056, 0x00000000000001b6)
writev(1, 0x00007fff009dc240, 2)
writev(1, 0x00007fff009dbb20, 2)
open('/home/runner/.nimble/packages_official.json', 557056, 0x00000000000001b6)
mkdir('/tmp/', 0x00000000000001ff)
mkdir('/tmp/nimble_2080/', 0x00000000000001ff)
mkdir('/tmp/nimble_2080/githubcom_stisajupyternim', 0x00000000000001ff)
writev(1, 0x00007fff009dbaf0, 2)
open('/tmp/nimble_2080/githubcom_stisajupyternim', 622592, 0x0000000000000000)
rmdir('/tmp/nimble_2080/githubcom_stisajupyternim')
writev(1, 0x00007fff009dba60, 2)
mkdir(94245805540400, 0x00000000000001ff)
Error tracing process: readBytes(0x000055b74fc2c430, 256) error: [Errno 5] Input/output error.
