     Info:  Nimble data file "/home/runner/.nimble/nimbledata2.json" has been loaded.
    Reading official package list
Downloading https://github.com/solaoi/voicepeaky4gpt using git
    Cloning latest tagged version: v1.0.0
open('/workspace/destdir/ssl/openssl.cnf', 32768, 0x00000000000001b6)
open('/home/runner/.config/nimble/nimble.ini', 557056, 0x00000000000001b6)
open('/home/runner/.config/babel/babel.ini', 557056, 0x00000000000001b6)
open('/home/runner/.nimble/nimbledata2.json', 557056, 0x00000000000001b6)
writev(1, 0x00007ffc671ab430, 2)
open('/home/runner/work/nim_packages_security_audit/nim_packages_security_audit', 622592, 0x0000000000000000)
writev(1, 0x00007ffc671aa060, 2)
open('/home/runner/.nimble/packages_official.json', 557056, 0x00000000000001b6)
mkdir('/tmp/', 0x00000000000001ff)
mkdir('/tmp/nimble_2534/', 0x00000000000001ff)
mkdir('/tmp/nimble_2534/githubcom_solaoivoicepeaky4gpt', 0x00000000000001ff)
open('/tmp/nimble_2534/githubcom_solaoivoicepeaky4gpt', 622592, 0x0000000000000000)
writev(1, 0x00007ffc671aa120, 2)
open('/tmp/nimble_2534/githubcom_solaoivoicepeaky4gpt', 622592, 0x0000000000000000)
rmdir('/tmp/nimble_2534/githubcom_solaoivoicepeaky4gpt')
writev(1, 0x00007ffc671aa010, 2)
mkdir(93952727521328, 0x00000000000001ff)
Error tracing process: readBytes(0x0000557312f31830, 256) error: [Errno 5] Input/output error.
